---
- name: create user cloud
  user: name="cloud"

- name: create boot_config directory
  file: path=/etc/csp/boot_config state=directory mode=0755 owner=centos group=centos recurse=yes

- name: create boot_scripts directory
  file: path=/etc/csp/boot_scripts state=directory mode=0755 owner=centos group=centos recurse=yes


- include: packages.yml

#- name: install yum-utils to have yum-config-manager utility
#  shell: "yum install yum-utils -y"
#- name: add docker-ce.repo
#  shell: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"
#- name: add docker-ce.repo
#  shell: "subscription-manager repos --enable=rhel-7-server-extras-rpms"
#- name: add docker-ce.repo
#  shell: "sudo yum install -y http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.95-2.el7_6.noarch.rpm"
  
#- name: install docker-engine package
#  shell: "yum install docker-ce-18.09.9-3.el7.x86_64 -y"
#- name: install docker-cli package
#  shell: "yum install docker-ce-cli-18.09.9-3.el7.x86_64 -y"
#- name: install containerd package
#  shell: "yum install containerd.io-1.2.111-3.2.el7.x86_64 -y"

#- name: curl get-docker.sh script
#  shell: "curl -fsSL https://get.docker.com -o get-docker.sh"
#- name: run get-docker.sh script
#  shell: "sh get-docker.sh"
  
#- name: how to add user to docker
#  shell: "usermod -a -G docker $USER"
